// This file was procedurally generated by Weaver. Any modifications will be overwritten.
// This file was generated using Weaver Lite. You can purchase Weaver Pro via the Welcome Panel in the Weaver Window.

#pragma warning disable // All.

/// <summary>This class was procedurally generated by Weaver.</summary>
public static class Animations
{
    #region Hash Constants

    /// <summary>Action</summary>
    public const int Action = 1080068516;

    /// <summary>Attack</summary>
    public const int Attack = 1080829965;

    /// <summary>Boss_Intro</summary>
    public const int Boss_Intro = -444724672;

    /// <summary>BossIntro</summary>
    public const int BossIntro = 1383474648;

    /// <summary>Cast1H</summary>
    public const int Cast1H = 141854322;

    /// <summary>Charge</summary>
    public const int Charge = 1388814594;

    /// <summary>ChargeAttack2H</summary>
    public const int ChargeAttack2H = -1183681289;

    /// <summary>Climb</summary>
    public const int Climb = -1670875122;

    /// <summary>Crouch</summary>
    public const int Crouch = -2015693266;

    /// <summary>Dead</summary>
    public const int Dead = 1293411866;

    /// <summary>Death</summary>
    public const int Death = 646380074;

    /// <summary>Default</summary>
    public const int Default = 753088835;

    /// <summary>DieBack</summary>
    public const int DieBack = -1078355538;

    /// <summary>DieFront</summary>
    public const int DieFront = 2012888654;

    /// <summary>Dissolve In</summary>
    public const int DissolveIn = 4948696;

    /// <summary>Dissolve Out</summary>
    public const int DissolveOut = -1596326684;

    /// <summary>Dissolve_In</summary>
    public const int Dissolve_In = 1608953269;

    /// <summary>Dissolve_Out</summary>
    public const int Dissolve_Out = -1819980754;

    /// <summary>DoTransitionToState1</summary>
    public const int DoTransitionToState1 = 1604672507;

    /// <summary>DoTransitionToState2</summary>
    public const int DoTransitionToState2 = -961803711;

    /// <summary>Gem Hover</summary>
    public const int GemHover = -737701023;

    /// <summary>Hidden</summary>
    public const int Hidden = -1879970677;

    /// <summary>Hit</summary>
    public const int Hit = 1654612129;

    /// <summary>HoldType</summary>
    public const int HoldType = -58195046;

    /// <summary>Hover</summary>
    public const int Hover = 991533264;

    /// <summary>Hurt</summary>
    public const int Hurt = 1740614436;

    /// <summary>Idle</summary>
    public const int Idle = 2081823275;

    /// <summary>IdleMelee</summary>
    public const int IdleMelee = 481432691;

    /// <summary>IsMoving</summary>
    public const int IsMoving = 120489994;

    /// <summary>Jab</summary>
    public const int Jab = 1561758614;

    /// <summary>JabMelee1H</summary>
    public const int JabMelee1H = 1851596232;

    /// <summary>JabMelee2H</summary>
    public const int JabMelee2H = 1164987915;

    /// <summary>JabMeleePaired</summary>
    public const int JabMeleePaired = 1865148686;

    /// <summary>Jump</summary>
    public const int Jump = 125937960;

    /// <summary>JumpTrigger</summary>
    public const int JumpTrigger = 113680519;

    /// <summary>Land</summary>
    public const int Land = 137525990;

    /// <summary>MagazineType</summary>
    public const int MagazineType = 1901757973;

    /// <summary>Move</summary>
    public const int Move = 1326225478;

    /// <summary>MoveBlend</summary>
    public const int MoveBlend = -1142910944;

    /// <summary>Ready</summary>
    public const int Ready = -380327253;

    /// <summary>ReadyBow</summary>
    public const int ReadyBow = 1301831853;

    /// <summary>ReadyBowCharge</summary>
    public const int ReadyBowCharge = 1858143143;

    /// <summary>ReadyBowRelease</summary>
    public const int ReadyBowRelease = -142972092;

    /// <summary>ReadyBowShot</summary>
    public const int ReadyBowShot = 1293291586;

    /// <summary>ReadyMelee1H</summary>
    public const int ReadyMelee1H = -616899283;

    /// <summary>ReadyMelee2H</summary>
    public const int ReadyMelee2H = -266891538;

    /// <summary>Run</summary>
    public const int Run = 1748754976;

    /// <summary>Slash</summary>
    public const int Slash = -972068619;

    /// <summary>SlashMelee1H</summary>
    public const int SlashMelee1H = 1130541514;

    /// <summary>SlashMelee2H</summary>
    public const int SlashMelee2H = 1750065673;

    /// <summary>SlashMeleePaired</summary>
    public const int SlashMeleePaired = 138539976;

    /// <summary>Speed</summary>
    public const int Speed = -823668238;

    /// <summary>Stand</summary>
    public const int Stand = -1518848078;

    /// <summary>State</summary>
    public const int State = 1649606143;

    /// <summary>State1</summary>
    public const int State1 = -1363389753;

    /// <summary>State2</summary>
    public const int State2 = 934609789;

    /// <summary>ThrowSupply</summary>
    public const int ThrowSupply = -67707850;

    /// <summary>UpperBodySpeed</summary>
    public const int UpperBodySpeed = -1658010338;

    /// <summary>UseSupply</summary>
    public const int UseSupply = 1105909183;

    /// <summary>VelocityY</summary>
    public const int VelocityY = -303020060;

    /// <summary>Victory</summary>
    public const int Victory = -1090111034;

    /// <summary>Visible</summary>
    public const int Visible = -1257385531;

    /// <summary>Walk</summary>
    public const int Walk = 765711723;

    /// <summary>Wall Hold Left</summary>
    public const int WallHoldLeft = -235799172;

    /// <summary>Wall Hold Right</summary>
    public const int WallHoldRight = -1365559437;

    /// <summary>Wall Slide Left</summary>
    public const int WallSlideLeft = -690687663;

    /// <summary>Wall Slide Right</summary>
    public const int WallSlideRight = -345813494;

    /// <summary>WallDirection</summary>
    public const int WallDirection = 64876659;

    /// <summary>WallHolding</summary>
    public const int WallHolding = 811265973;

    /// <summary>WallSliding</summary>
    public const int WallSliding = 469228127;

    /// <summary>WeaponType</summary>
    public const int WeaponType = -1936256502;

    /// <summary>Get the name of the specified 'state' using HashToString.</summary>
    public static string GetName(this UnityEngine.AnimatorStateInfo state) => HashToString(state.shortNameHash);

    /// <summary>Get the state or parameter name associated with the specified 'hash' value.</summary>
    public static string HashToString(int hash)
    {
        switch (hash)
        {
            case GemHover: return "Gem Hover";
            case Default: return "Default";
            case Hover: return "Hover";
            case DissolveIn: return "Dissolve In";
            case DissolveOut: return "Dissolve Out";
            case Visible: return "Visible";
            case Hidden: return "Hidden";
            case Dissolve_In: return "Dissolve_In";
            case Dissolve_Out: return "Dissolve_Out";
            case Idle: return "Idle";
            case Attack: return "Attack";
            case Walk: return "Walk";
            case Death: return "Death";
            case Run: return "Run";
            case Ready: return "Ready";
            case Hurt: return "Hurt";
            case BossIntro: return "BossIntro";
            case Action: return "Action";
            case State: return "State";
            case Speed: return "Speed";
            case Boss_Intro: return "Boss_Intro";
            case ReadyBow: return "ReadyBow";
            case ReadyBowCharge: return "ReadyBowCharge";
            case ReadyBowRelease: return "ReadyBowRelease";
            case IdleMelee: return "IdleMelee";
            case SlashMelee1H: return "SlashMelee1H";
            case ReadyMelee1H: return "ReadyMelee1H";
            case JabMelee1H: return "JabMelee1H";
            case ReadyMelee2H: return "ReadyMelee2H";
            case SlashMelee2H: return "SlashMelee2H";
            case JabMelee2H: return "JabMelee2H";
            case Cast1H: return "Cast1H";
            case ChargeAttack2H: return "ChargeAttack2H";
            case SlashMeleePaired: return "SlashMeleePaired";
            case Victory: return "Victory";
            case JabMeleePaired: return "JabMeleePaired";
            case UseSupply: return "UseSupply";
            case ThrowSupply: return "ThrowSupply";
            case Hit: return "Hit";
            case ReadyBowShot: return "ReadyBowShot";
            case Stand: return "Stand";
            case Crouch: return "Crouch";
            case Climb: return "Climb";
            case DieBack: return "DieBack";
            case DieFront: return "DieFront";
            case Jump: return "Jump";
            case WallSlideRight: return "Wall Slide Right";
            case WallHoldLeft: return "Wall Hold Left";
            case WallHoldRight: return "Wall Hold Right";
            case WallSlideLeft: return "Wall Slide Left";
            case Slash: return "Slash";
            case Jab: return "Jab";
            case Dead: return "Dead";
            case WeaponType: return "WeaponType";
            case MagazineType: return "MagazineType";
            case HoldType: return "HoldType";
            case Charge: return "Charge";
            case UpperBodySpeed: return "UpperBodySpeed";
            case VelocityY: return "VelocityY";
            case JumpTrigger: return "JumpTrigger";
            case Land: return "Land";
            case WallSliding: return "WallSliding";
            case WallHolding: return "WallHolding";
            case WallDirection: return "WallDirection";
            case Move: return "Move";
            case MoveBlend: return "MoveBlend";
            case IsMoving: return "IsMoving";
            case State1: return "State1";
            case State2: return "State2";
            case DoTransitionToState1: return "DoTransitionToState1";
            case DoTransitionToState2: return "DoTransitionToState2";
            default: return null;
        }
    }

    #endregion
}
