// This file was procedurally generated by Weaver.Editor.Procedural.BuildDetailsScriptBuilder.GenerateScript. Any modifications will be overwritten.
// This file was generated using Weaver Lite. You can purchase Weaver Pro via the Welcome Panel in the Weaver Window.

#pragma warning disable // All.

/// <summary>
/// A utility class which tracks the number of times this project has been built and the date it was last built.
/// This class is automatically regenerated each time the project is built.
/// </summary>
public static class BuildDetails
{
    /// <summary>The number of times this project has been built.</summary>
    public const int BuildNumber = -1;

    /// <summary>31/03/2024 2:09:14 PM</summary>
    public static readonly System.DateTime BuildDate = new System.DateTime(638474909544241985L);
}
