// This file was procedurally generated by Weaver. Any modifications will be overwritten.
// This file was generated using Weaver Lite. You can purchase Weaver Pro via the Welcome Panel in the Weaver Window.

#pragma warning disable // All.

/// <summary>This class was procedurally generated by Weaver.</summary>
public static class Layers
{
    #region Layers -> Edit/Project Settings/Tags and Layers

    /// <summary>Default (Mask Value = 1)</summary>
    public const int Default = 0;

    /// <summary>TransparentFX (Mask Value = 2)</summary>
    public const int TransparentFX = 1;

    /// <summary>Ignore Raycast (Mask Value = 4)</summary>
    public const int IgnoreRaycast = 2;

    /// <summary>Water (Mask Value = 16)</summary>
    public const int Water = 4;

    /// <summary>UI (Mask Value = 32)</summary>
    public const int UI = 5;

    /// <summary>Camera (Mask Value = 128)</summary>
    public const int Camera = 7;

    /// <summary>Climbable (Mask Value = 256)</summary>
    public const int Climbable = 8;

    /// <summary>Ground (Mask Value = 512)</summary>
    public const int Ground = 9;

    /// <summary>Sensors (Mask Value = 1024)</summary>
    public const int Sensors = 10;

    /// <summary>Damageable (Mask Value = 2048)</summary>
    public const int Damageable = 11;

    /// <summary>Player (Mask Value = 4096)</summary>
    public const int Player = 12;

    #endregion
}
