// This file was procedurally generated by Weaver. Any modifications will be overwritten.
// This file was generated using Weaver Lite. You can purchase Weaver Pro via the Welcome Panel in the Weaver Window.

#pragma warning disable // All.

/// <summary>This class was procedurally generated by Weaver.</summary>
public static class Tags
{
    public const string Untagged = "Untagged";

    public const string Respawn = "Respawn";

    public const string Finish = "Finish";

    public const string EditorOnly = "EditorOnly";

    public const string MainCamera = "MainCamera";

    public const string Player = "Player";

    public const string GameController = "GameController";

    public const string Ground = "Ground";

    public const string Spike = "Spike";
}
