// This file was procedurally generated by Weaver.

namespace Weaver
{
    /// <summary>An <see cref="AssetList{T}"/> of <see cref="Weaver.Examples.Missile"/> prefabs.</summary>
    public sealed class MissileList : Weaver.AssetList<Weaver.Examples.Missile> { }
}
