// This file was procedurally generated by Weaver.

namespace Weaver
{
    /// <summary>
    /// A <see cref="MetaAssetList{TAsset, TMeta}"/> of <see cref="Weaver.Examples.Item"/> prefabs and their
    /// <see cref="Weaver.Examples.ItemMetaData"/>.
    /// </summary>
    public sealed class ItemList : Weaver.MetaAssetList<Weaver.Examples.Item, Weaver.Examples.ItemMetaData> { }
}
